### PR TITLE
Reverted header bytes calculation

### PR DESCRIPTION
**Pull request by bspaulding**
Reverted for now, until I have time to make a proper fix.

### CODE REVIEW

**Comment by tbuchok** [comment]
thanks. noticed that tests fail on node 4.1, ill update master with those edits, just init'ing a buffer w/o an arg in the sync fn.

**Comment by bspaulding** [comment]
ah, gotcha. I was wondering what the heck that error meant. Not as familiar with node. Sweet.

**Comment by tbuchok** [comment]
made that fix at ecb4f7639789978ee0abc47cebd0bcbb8613c9d3 if interested. exciting stuff!!

**Comment by tbuchok** [comment]
published at 1.1.4 on npm https://www.npmjs.com/package/animated-gif-detector

thanks for the follow up on this and looking into -- futzing with bytes is kind of fun/annoying at the same time.

**Pull request merged**
