### PR TITLE
WIP: Stop walking through buffer if it's a non-GIF

### PR DESCRIPTION
**Pull request by automata**
If we are reading the first bytes of the buffer and its signature says it's not a GIF, we don't need to go ahead. In situations like with big non-GIF images we need to wait until the end of file just to discover it's not a GIF and obviously not animated.

What's your opinion @tbuchok?

### CODE REVIEW

**Comment by tbuchok** [comment]
@automata this makes sense -- do you think we even need a pointer on `this.chunks` at all? just returning immediately if `this.isGIF === false`?

basically, [removing these lines](https://github.com/automata/animated-gif-detector/blob/master/index.js#L58-L62)?

**Comment by tbuchok** [comment]
looks like we can also stop "walking" if it's animated, here's what i'm thinking:

```js
AnimatedGifDetector.prototype._write = function(chunk, enc, next) {
  this.buffer = Buffer.concat([this.buffer, chunk])
    , animated = this.isAnimated(this.buffer)
  ;

  if (this.buffer.length > 4)
    this.isGIF = this.buffer.slice(0, 3).toString() === 'GIF';

  // If it's the first chunk of stream we analyze and is not GIF, stop
  if (this.isGIF === false)
    return this.emit('finish');

  if (animated) {
    this.emit('animated');
    return this.emit('finish');
  }

  next();
};
```

i'm not sure i'm good enough at github to issue a PR against your PR, so if we want to merge yours and then make further updates, that's cool too. let me know what you think.

**Comment by automata** [comment]
@tbuchok yeah, that makes sense too, I'll update and push.

**Comment by tbuchok** [comment]
i see, the `chunks` counter may be helpful so we're not continually slicing :hocho: to detect a GIF -- simply not init'ing `this.isGIF` and and using `undefined` could prevent that without additional props:

```js
// delete `this.isGIF = false` in ctor ...

if (this.buffer.length > 4 && this.isGIF == undefined) // slice and determine if `isGIF`
```

not sure your use case and if this helps with perf or not?

**Comment by automata** [comment]
Yeah, please do not merge yet, I'll investigate your suggestions further and back to you in some minutes. Thank you for the suggestions.

**Comment by tbuchok** [comment]
keep me posted @automata -- i'll be offline most of today (vacation :palm_tree:) -- but will take a look when i return. thanks for the helpful code and input on this!

**Comment by automata** [comment]
@tbuchok I accepted your suggestions: removed the initialization of `isGIF` property and now we `finish` also when we find it's animated.

**Comment by tbuchok** [comment]
thanks for this, i've also landed a test for this use case at https://github.com/mailcharts/animated-gif-detector/commit/89badb0271a6a663d50e4b0b28f45b129a4ae790

bumped to npm [@1.1.5](https://www.npmjs.com/package/animated-gif-detector)

let me know any problems!

**Comment by automata** [comment]
Amazing, thank you!

**Pull request merged**
