### PR TITLE
Optimize performance for large size gif images

### PR DESCRIPTION
**Pull request by paras20xx**
Large size gif images, especially the non-animated ones, were not behaving in an optimized manner because each _write operation was starting detection from the beginning of the buffer.

### CODE REVIEW

**Comment by paras20xx** [comment]
If you find it all good, kindly publish a new npm version, will use the updated version in https://www.npmjs.com/package/express-processimage

**Comment by tbuchok** [comment]
@paras20xx will add a commit for contributors, and then finally publish. 5m or so from now. thanks for putting in the work and clear tests for this. very much appreciated.

**Comment by tbuchok** [comment]
[animated-gift-detector@1.2](https://www.npmjs.com/package/animated-gif-detector) is published -- thanks again @paras20xx

**Comment by paras20xx** [comment]
Thanks a lot for quick response :-)

**Pull request merged**
